In [104]:
import math
import numpy as np
from numpy.testing import assert_allclose
import time
from passive_extended_matchgate_simulator.exact import exact_calculation
from passive_extended_matchgate_simulator.utils import (ucj_to_compatible, 
                                                        ucj_to_compatible_fully_reduced, 
                                                        get_bitstrings_and_probs, 
                                                        make_parameterized_controlled_phase_circuit,
                                                        extract_circuit_data)

mean, var = math.pi, .1
norb, nelec = 6, (3,3)


circuit = make_parameterized_controlled_phase_circuit(norb, nelec, mean, var, reduced_interaction=False)
bitstrings, exact_probs = get_bitstrings_and_probs(circuit, norb, nelec)

In [105]:
exact_probs

array([1.95136288e-02, 1.15823188e-04, 3.78800609e-03, 6.10770324e-03,
       2.22235565e-03, 9.67885625e-04, 2.46869833e-03, 1.28940996e-03,
       2.59857380e-04, 1.58314648e-05, 4.07801532e-03, 1.93775377e-02,
       2.84830200e-04, 5.71607799e-03, 6.09861971e-04, 5.82540916e-03,
       8.10066191e-03, 1.46222653e-03, 2.85304152e-03, 9.00407138e-04,
       1.15823188e-04, 2.50214028e-03, 6.49693046e-03, 8.04537478e-05,
       3.42897198e-03, 5.93100387e-03, 5.08160612e-04, 3.01646884e-04,
       6.76242920e-04, 4.06209120e-04, 1.22275049e-04, 1.69288439e-03,
       1.38789334e-04, 2.45132374e-04, 5.24559141e-04, 6.77051704e-04,
       2.77825455e-03, 2.76361573e-04, 1.15135399e-04, 1.97228846e-05,
       3.78800609e-03, 6.49693046e-03, 2.04323450e-02, 1.24692064e-02,
       1.91261950e-02, 1.44330933e-02, 1.30593335e-04, 5.48904989e-03,
       1.11058055e-04, 2.86916942e-03, 1.53390036e-02, 4.21762334e-03,
       5.11411855e-03, 7.33133099e-03, 1.49646994e-03, 1.47894956e-02,
      

In [106]:
compatible = ucj_to_compatible(circuit)
t1 = time.perf_counter()
probs_compatible = exact_calculation(circuit=compatible, outcome_states=bitstrings)
t2 = time.perf_counter()
assert_allclose(probs_compatible, exact_probs)
print('time:', t2 - t1)
probs_compatible

time: 2.2686539170099422


array([1.95136288e-02, 1.15823188e-04, 3.78800609e-03, 6.10770324e-03,
       2.22235565e-03, 9.67885625e-04, 2.46869833e-03, 1.28940996e-03,
       2.59857380e-04, 1.58314648e-05, 4.07801532e-03, 1.93775377e-02,
       2.84830200e-04, 5.71607799e-03, 6.09861971e-04, 5.82540916e-03,
       8.10066191e-03, 1.46222653e-03, 2.85304152e-03, 9.00407138e-04,
       1.15823188e-04, 2.50214028e-03, 6.49693046e-03, 8.04537478e-05,
       3.42897198e-03, 5.93100387e-03, 5.08160612e-04, 3.01646884e-04,
       6.76242920e-04, 4.06209120e-04, 1.22275049e-04, 1.69288439e-03,
       1.38789334e-04, 2.45132374e-04, 5.24559141e-04, 6.77051704e-04,
       2.77825455e-03, 2.76361573e-04, 1.15135399e-04, 1.97228846e-05,
       3.78800609e-03, 6.49693046e-03, 2.04323450e-02, 1.24692064e-02,
       1.91261950e-02, 1.44330933e-02, 1.30593335e-04, 5.48904989e-03,
       1.11058055e-04, 2.86916942e-03, 1.53390036e-02, 4.21762334e-03,
       5.11411855e-03, 7.33133099e-03, 1.49646994e-03, 1.47894956e-02,
      

In [107]:
compatible_fully_reduced = ucj_to_compatible_fully_reduced(circuit)
t1 = time.perf_counter()
probs_compatible_fully_reduced = exact_calculation(circuit=compatible_fully_reduced, outcome_states=bitstrings)
t2 = time.perf_counter()
assert_allclose(probs_compatible_fully_reduced, exact_probs)
print('time', t2 - t1)
probs_compatible_fully_reduced

time 2.2385089580202475


array([1.95136288e-02, 1.15823188e-04, 3.78800609e-03, 6.10770324e-03,
       2.22235565e-03, 9.67885625e-04, 2.46869833e-03, 1.28940996e-03,
       2.59857380e-04, 1.58314648e-05, 4.07801532e-03, 1.93775377e-02,
       2.84830200e-04, 5.71607799e-03, 6.09861971e-04, 5.82540916e-03,
       8.10066191e-03, 1.46222653e-03, 2.85304152e-03, 9.00407138e-04,
       1.15823188e-04, 2.50214028e-03, 6.49693046e-03, 8.04537478e-05,
       3.42897198e-03, 5.93100387e-03, 5.08160612e-04, 3.01646884e-04,
       6.76242920e-04, 4.06209120e-04, 1.22275049e-04, 1.69288439e-03,
       1.38789334e-04, 2.45132374e-04, 5.24559141e-04, 6.77051704e-04,
       2.77825455e-03, 2.76361573e-04, 1.15135399e-04, 1.97228846e-05,
       3.78800609e-03, 6.49693046e-03, 2.04323450e-02, 1.24692064e-02,
       1.91261950e-02, 1.44330933e-02, 1.30593335e-04, 5.48904989e-03,
       1.11058055e-04, 2.86916942e-03, 1.53390036e-02, 4.21762334e-03,
       5.11411855e-03, 7.33133099e-03, 1.49646994e-03, 1.47894956e-02,
      

In [108]:
print('max compatible difference', max(abs(np.array(probs_compatible) - np.array(exact_probs))))
print('max compatible reduced difference', max(abs(np.array(probs_compatible_fully_reduced) - np.array(exact_probs))))

max compatible difference 2.983724378680108e-16
max compatible reduced difference 1.9081958235744878e-16
